### ISSUE TITLE
 Add library

### ISSUE THREAD

**Issue by 943fansi** [DaoSword/Time-Series-Forecasting-and-Deep-Learning#10]
1. Machine learning for transportation data imputation and prediction
[transdim](https://github.com/xinychen/transdim)

2. A Python package to discover stochastic differential equations from time series data
[PyDaddy](https://github.com/tee-lab/PyDaddy)

3. pyclustering is a Python, C++ data mining library
[pyclustering](https://github.com/annoviko/pyclustering)

**Comment by DaoSword** [comment]
transdim and PyDaddy added.
Since pyclustering is a more general data science library, I have added it to my other project [Data Science Collections](https://github.com/DaoSword/data-science-collections).
