### ISSUE TITLE
Replace neuralprophet link

### ISSUE THREAD

**Issue by 943fansi** [DaoSword/Time-Series-Forecasting-and-Deep-Learning#18]
Unable to access https://neuralprophet.com/html/index.html, use https://github.com/ourownstory/neural_prophet to replace.

**Comment by 943fansi** [comment]
By the way, Teacher Chen shared on Weibo https://weibo.com/1402400261/MBP855XuC.

**Comment by DaoSword** [comment]
> By the way, Teacher Chen shared on Weibo https://weibo.com/1402400261/MBP855XuC.

@943fansi wow, that's so cool! I have been following Teacher Chen's Bilibili account for a long time, and I learned a lot from many lecture videos and resources he shared. Really appreciate it.

**Comment by DaoSword** [comment]
> Unable to access https://neuralprophet.com/html/index.html, use https://github.com/ourownstory/neural_prophet to replace.

@943fansi NeuralProphet's link and description have been updated.
