### ISSUE TITLE
add paper

### ISSUE THREAD

**Issue by 943fansi** [DaoSword/Time-Series-Forecasting-and-Deep-Learning#27]
Unsupervised Representation Learning for Time Series: A Review
https://github.com/mqwfrog/ULTS

Automatic Feature Engineering for Time Series Classification: Evaluation and Discussion
https://github.com/aurelien-renault/Automatic-Feature-Engineering-for-TSC

DEEPTSF: CODELESS MACHINE LEARNING OPERATIONS FOR TIME SERIES FORECASTING
https://github.com/I-NERGY/DeepTSF

Enhancing Representation Learning for Periodic Time Series with Floss: A Frequency Domain Regularization Approach
https://github.com/agustdd/floss

**Comment by DaoSword** [comment]
ULTS paper added.

**Comment by DaoSword** [comment]
Automatic-Feature-Engineering-for-TSC paper added.

**Comment by DaoSword** [comment]
DeepTSF paper added.

**Comment by DaoSword** [comment]
Floss paper added.
