### ISSUE TITLE
A little issue

### ISSUE THREAD

**Issue by lss-1138** [DaoSword/Time-Series-Forecasting-and-Deep-Learning#35]
Thank you for your excellent repository!

We noticed that you included the article [Efficient and Effective Time-Series Forecasting with Spiking Neural Networks], but the provided official code link points to our SparseTSF repository. It seems there might be an issue here. Could you please correct it? Thank you!

https://github.com/DaoSword/Time-Series-Forecasting-and-Deep-Learning/blob/00b37fca9908aa8e4193542d291c769390b11a1b/README.md?plain=1#L72-L76

**Comment by DaoSword** [comment]
I have added the corresponding SparseTSF paper and removed the wrong link. Thank you for pointing out the mistake!
