### ISSUE TITLE
Add papers

### ISSUE THREAD

**Issue by 943fansi** [DaoSword/Time-Series-Forecasting-and-Deep-Learning#6]
1. [Reconstructing Nonlinear Dynamical Systems from Multi-Modal Time Series](https://arxiv.org/abs/2111.02922)
code [https://github.com/DurstewitzLab/mmPLRNN](https://github.com/DurstewitzLab/mmPLRNN)
2. [Closed-Form Diffeomorphic Transformations for Time Series Alignment](https://arxiv.org/abs/2206.08107)
code [https://github.com/imartinezl/difw](https://github.com/imartinezl/difw)
3. [Domain Adaptation for Time Series Forecasting via Attention Sharing](https://arxiv.org/abs/2102.06828)
code [https://github.com/DMIRLAB-Group/SASA](https://github.com/DMIRLAB-Group/SASA)
4. [Learning of Cluster-based Feature Importance for Electronic Health Record Time-series](https://proceedings.mlr.press/v162/aguiar22a.html)
code [https://github.com/hrna-ox/camelot-icml](https://github.com/hrna-ox/camelot-icml)
5. [Adaptive Conformal Predictions for Time Series](https://arxiv.org/abs/2202.07282)
code [https://github.com/mzaffran/AdaptiveConformalPredictionsTimeSeries](https://github.com/mzaffran/AdaptiveConformalPredictionsTimeSeries)
6. [Utilizing Expert Features for Contrastive Learning of Time-Series Representations](https://arxiv.org/abs/2206.11517)
code [https://github.com/boschresearch/expclr](https://github.com/boschresearch/expclr)
7. [Modeling Irregular Time Series with Continuous Recurrent Units](https://arxiv.org/abs/2111.11344)
code [https://github.com/boschresearch/Continuous-Recurrent-Units](https://github.com/boschresearch/Continuous-Recurrent-Units)

**Comment by DaoSword** [comment]
7 papers added.
